export const CARD_LANGUAGES = [
  { code: "de", label: "Deutsch" },
  { code: "en", label: "English" },
  { code: "fr", label: "Français" },
  { code: "es", label: "Español" },
  { code: "it", label: "Italiano" },
  { code: "ja", label: "日本語" },
] as const;

export type CardLanguage = (typeof CARD_LANGUAGES)[number]["code"];

export const DEFAULT_LANGUAGE: CardLanguage = "de";

export const RARITIES_BY_LANG: Record<CardLanguage, string[]> = {
  de: [
    "Alle Seltenheiten",
    "Häufig",
    "Ungewöhnlich",
    "Selten",
    "Selten, Holografisch",
    "Ultra Selten",
    "Doppel Rare",
    "Illustration Rare",
    "Special Illustration Rare",
    "Hyper Rare",
    "Promo",
    "Keine",
  ],
  en: [
    "Alle Seltenheiten",
    "Common",
    "Uncommon",
    "Rare",
    "Rare Holo",
    "Double Rare",
    "Ultra Rare",
    "Special Illustration Rare",
    "Hyper Rare",
    "Promo",
  ],
  fr: [
    "Alle Seltenheiten",
    "Commune",
    "Peu Commune",
    "Rare",
    "Rare Holo",
    "Double Rare",
    "Ultra Rare",
    "Promo",
  ],
  es: [
    "Alle Seltenheiten",
    "Común",
    "Poco común",
    "Rara",
    "Rara Holo",
    "Promo",
  ],
  it: [
    "Alle Seltenheiten",
    "Comune",
    "Non comune",
    "Rara",
    "Rara Holo",
    "Promo",
  ],
  ja: [
    "Alle Seltenheiten",
    "Common",
    "Uncommon",
    "Rare",
    "Rare Holo",
    "Double Rare",
    "Ultra Rare",
    "Special Illustration Rare",
    "Hyper Rare",
    "None",
    "Promo",
  ],
};

export const COLORS_BY_LANG: Record<CardLanguage, string[]> = {
  de: [
    "Alle Farben",
    "Pflanze",
    "Feuer",
    "Wasser",
    "Elektro",
    "Psycho",
    "Kampf",
    "Finsternis",
    "Metall",
    "Fee",
    "Drache",
    "Farblos",
  ],
  en: [
    "All Colors",
    "Grass",
    "Fire",
    "Water",
    "Lightning",
    "Psychic",
    "Fighting",
    "Darkness",
    "Metal",
    "Fairy",
    "Dragon",
    "Colorless",
  ],
  fr: [
    "Toutes les couleurs",
    "Plante",
    "Feu",
    "Eau",
    "Électrique",
    "Psy",
    "Combat",
    "Obscurité",
    "Métal",
    "Fée",
    "Dragon",
    "Incolore",
  ],
  es: [
    "Todos los colores",
    "Planta",
    "Fuego",
    "Agua",
    "Rayo",
    "Psíquica",
    "Lucha",
    "Oscuridad",
    "Metal",
    "Hada",
    "Dragón",
    "Incolora",
  ],
  it: [
    "Tutti i colori",
    "Erba",
    "Fuoco",
    "Acqua",
    "Lampo",
    "Psico",
    "Lotta",
    "Oscurità",
    "Metallo",
    "Folletto",
    "Drago",
    "Incolore",
  ],
  ja: [
    "すべてのタイプ",
    "草",
    "炎",
    "水",
    "雷",
    "超",
    "闘",
    "悪",
    "鋼",
    "妖",
    "ドラゴン",
    "無色",
  ],
};

export function isCardLanguage(value: string): value is CardLanguage {
  return CARD_LANGUAGES.some((l) => l.code === value);
}